---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-westermanonline-com
  namespace: overseerr
spec:
  secretName: local-westermanonline-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.westermanonline.com"
  dnsNames:
  - "local.westermanonline.com"
  - "*.local.westermanonline.com"
