---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: westermanonline-com
  namespace: default
spec:
  secretName: local-westermanonline-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.westermanonline.com"
  dnsNames:
  - "local.westermanonline.com"
  - "*.local.westermanonline.com"
