---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-westermanonline-com
  namespace: default
spec:
  secretName: westermanonline-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.westermanonline.com"
  dnsNames:
  - "westermanonline.com"
